### ISSUE TITLE
Device proxy

### ISSUE THREAD

**Issue by vikram919** [fhnw-bacnet-it/ase#4]
BACnet/IT draft supports device proxy functionality for interoperability with existing BACnet/NL devices, I see that currently device proxy is not implemented in current stack? If not do this repo has plans of implementing I can make a pull request for that?

**Comment by wweck** [comment]
Discussion by the standardization committee moved away from this BACnet/IT draft, mostly because of the need for this additional proxy to BACnet/NL. Industry decided the trade-off in favor of the traditional architecture (retaining segmentation of messages) to avoid investments into new proxy development.
Hence we are currently not further developing this BACnet/IT implementation.
